src/Entity/HeUser.php
<?php

namespace App\Entity;

use App\Entity\HeRole;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Traits\Timestampable;
use App\Repository\HeUserRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

/**
 * @ORM\Entity(repositoryClass=HeUserRepository::class)
 * @ORM\Table(name="he_users")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 * @ORM\HasLifecycleCallbacks
 * @Vich\Uploadable
 */
class HeUser implements UserInterface, PasswordAuthenticatedUserInterface
{

    use Timestampable;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank(message="Cette valeur ne doit pas être vide.")
     * @Assert\Email()
     */
    private $email;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastName;

    /**
     * @ORM\Column(type="datetime", length=255, nullable=true)
     */
    private $birthDate;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $birthPlace;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phoneNumber;


    /**
     * @ORM\ManyToMany(targetEntity=HeRole::class, inversedBy="heUsers")
     */
    private $heRoles;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * 
     */
    private $avatar;

    /**
     * @Vich\UploadableField(mapping="avatars", fileNameProperty="avatar")
     * @Assert\NotBlank(message="Vous devez avoir une image.")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $confirmAt;


    /**
     * @ORM\Column(type="boolean")
     */
    private $isDeleted;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\ManyToOne(targetEntity=HeStudentInformation::class, inversedBy="users")
     */
    private $studentInformation;



    public function __construct()
    {
        $this->heRoles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, HeRole>
     */
    public function getHeRoles(): Collection
    {
        return $this->heRoles;
    }

    public function addHeRole(HeRole $heRole): self
    {
        if (!$this->heRoles->contains($heRole)) {
            $this->heRoles[] = $heRole;
        }

        return $this;
    }

    public function removeHeRole(HeRole $heRole): self
    {
        $this->heRoles->removeElement($heRole);

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $userRoles = $this->getHeRoles();
        $roles = [];
        foreach ($userRoles as $userRole) {
            $roles[] = $userRole->getName();
        }
        return array_unique($roles);
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function isIsDeleted(): ?bool
    {
        return $this->isDeleted;
    }

    public function setIsDeleted(bool $isDeleted): self
    {
        $this->isDeleted = $isDeleted;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function getFullName()
    {
        return $this->firstName . ' ' . $this->lastName;
    }

    public function getFullBirth()
    {

        return $this->birthDate->format('d-m-Y') . ' à ' . $this->birthPlace;
    }

    public function getConfirmAt(): ?\DateTimeInterface
    {
        return $this->confirmAt;
    }

    public function setConfirmAt(?\DateTimeInterface $confirmAt): self
    {
        $this->confirmAt = $confirmAt;

        return $this;
    }

    public function getBirthDate(): ?\DateTime
    {
        return $this->birthDate;
    }

    public function setBirthDate(\DateTime $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getBirthPlace(): ?string
    {
        return $this->birthPlace;
    }

    public function setBirthPlace(string $birthPlace): self
    {
        $this->birthPlace = $birthPlace;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function getStudentInformation(): ?HeStudentInformation
    {
        return $this->studentInformation;
    }

    public function setStudentInformation(?HeStudentInformation $studentInformation): self
    {
        $this->studentInformation = $studentInformation;

        return $this;
    }
}

src/Controller/SchoolManager/SchoolManagerController.php
<?php

namespace App\Controller\SchoolManager;

use DateTime;
use App\Entity\HePayment;
use Symfony\Component\Mime\Email;
use App\Repository\HeUserRepository;
use App\Repository\HePaymentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/school-manager", priority=10)
 */
class SchoolManagerController extends AbstractController
{
    /**
     * @Route("/", name="app_school_manager_home")
     */
    public function index(): Response
    {
        return $this->render('school_manager/dashboard.html.twig');
    }

    /**
     * @Route("/payment/request/{type}", name="app_school_manager_payment_request")
     */
    public function paymentRequest(?string $type, Request $request, HePaymentRepository $hePaymentRepository): Response
    {
        $requests = $hePaymentRepository->getRequestUnReadByType($type);
        return $this->render('school_manager/payment/request.html.twig', [
            'requests' => $requests,
            'type' => $type
        ]);
    }


    /**
     * @Route("/payment/validate/{id}", name="app_payment_validate")
     */
    public function paymentValidate(
        HePayment $hePayment,
        Request $request,
        MailerInterface $mailer,
        EntityManagerInterface $entityManagerInterface,
        HeUserRepository $heUserRepository
    ): Response {
        $hePayment
            ->setState('read')
            ->setDecision('taken')
            ->setObservation($request->request->get('observation_' . $hePayment->getId()))
            ->setValidatedAt(new \DateTime());
        $studentInformation = $hePayment->getStudent();
        switch ($hePayment->getReason()) {
            case 'registration-fee':
                $studentInformation->setRegistrationFee(1);
                break;
            case 'monthly-fees':
                $studentInformation->setMonthlyFees($studentInformation->getMonthlyFees() + ($hePayment->getAmount() / 200000));
                break;
        }
        $student = $heUserRepository->getUserByStudentInformation($studentInformation);
        $email = (new TemplatedEmail())
            ->from('aeli@gmail.com')
            ->to($student->getEmail())
            ->subject('aeli paiement : ' . $this->getReasonPayment($hePayment->getReason()) . ' par MVOLA')
            ->htmlTemplate("school_manager/payment/email-template.html.twig")
            ->context([
                'reason' =>  $hePayment->getReason(),
                'id' =>  $hePayment->getId(),
                'student' => $student
            ]);
        $mailer->send($email);
        $entityManagerInterface->flush();
        $this->addFlash('success', "Une demande a été validé avec succèss, IDENTIFICATION : " . $hePayment->getId());
        return $this->redirectToRoute('app_school_manager_payment_request', ['type' => $hePayment->getType()]);
    }


    public function getReasonPayment($reason)
    {
        return [
            'registration-fee' => 'Frais d\'inscription',
            'monthly-fees' => 'Écolage',
        ][$reason];
    }
}

templates/school_manager/payment/email-template.html.twig
<html>
	<body>
		<div style="flex-direction:row;display:flex;margin:0;padding:0;height: 100px; background:linear-gradient(90deg,rgb(4, 94, 110) 26%,#a5010147 150%);">
			<h1 style="width:100%;color: white; opacity: 0.8; text-align:center;font-size:40px;word-wrap: break-word;">
				Aeli Africa Département finance
			</h1>
		</div>

		<h2 style="font-size: 30px; color: green; font-weight: bolder;text-align: center; font-style: italic;">Validation "
			{{ getReason(reason) }}
			" effectuée</h2>
		<p style="text-align: center; font-size: 20px;text-justify: distribute;">
			<strong>Félicitation!!!
				{{ student.fullname }}
			</strong>
			<br>
			Votre paiement par MVOLA pour la validation de votre
			{{ getReason(reason) }}
			a été effectuée avec succès [ Identification :
			{{ id }}
			].
			<br>
			L' université Aeli Africa vous remercie de votre confiance.
			<br>
		</p>
		<div style="text-align: end; font-style: italic;">
			<strong>Aeli Africa Finance</strong>
		</div>
	</body>
</html>

templates/school_manager/payment/request.html.twig
{% extends "school_manager/sm.html.twig" %}

{% block stylesheets %}
	<style></style>

{% endblock %}

{% block title %}
	Demande de validation de paiment via mobile money ~
	{{parent()}}
{% endblock %}

{% block body %}
	<div class="wrapper">

		{{ include('school_manager/layouts/nav-bar.html.twig') }}
		{{ include('school_manager/layouts/aside-bar.html.twig') }}

		<div class="content-wrapper">

			<section class="content-header">
				<div class="container-fluid">
					<div class="row mb-2">
						<div class="col-sm-6">
							<h1 class="m-0 text-uppercase">Demande de validation de paiment</h1>
						</div>
						<!-- /.col -->
						<div class="col-sm-6">
							<ol class="breadcrumb float-sm-right">
								<li class="breadcrumb-item active">Gestionnaire d'écolage</li>
							</ol>
						</div>
					</div>
				</div>
			</section>

			<section class="content">
				<div class="container-fluid">
					<div class="row">
						<div class="col-lg-12">
							{% include "school_manager/layouts/_flashMessage.html.twig" %}
						</div>
					</div>
				</div>
				<div class="container-fluid">
					<div class="row">
						<div class="col-lg-12">
							<div class="card">
								<div class="card-header card-outline card-success">
									<h3 class="card-title">Liste de touts les demandes de paiments non-lu via :
										<span class="badge badge-success text-uppercase">{{ type }}</span>
									</h3>
								</div>
								<div class="card-body">
									<table id="example1" class="table table-bordered table-striped table-sm text-center">
										<thead>
											<tr>
												<th>Photo d'indentité</th>
												<th>Matricule</th>
												<th>Nom complet</th>
												<th>Semestre</th>
												<th>Status écolage</th>
												<th>Status inscription</th>
												<th>Motif</th>
												<th>Référence</th>
												<th>Date de paiment</th>
												<th>Montant</th>
												<th>Actions</th>
											</tr>
										</thead>
										<tbody>
											{% for request in requests %}
												{% set student = request.student %}
												{% set user = getUser(student) %}
												<tr>
													<td>
														{% if user.avatar is defined and user.avatar is not empty %}<img src="{{ vich_uploader_asset(user) | imagine_filter('AVATAR') }}" class="img-circle elevation-2" alt="User Image">{% else %}<img src="{{ asset('images/user-default-image.png') }}" class="img-circle elevation-2" alt="User Image">
														{% endif %}
													</td>
													<td>
														{{ student.matriculeNumber }}
													</td>
													<td>
														{{ user.fullName }}
													</td>
													<td>
														{{ student.semester }}
													</td>
													<td>
														{{ student.monthlyFees }}
														/
														{{ getMaxNumberMonthlyFeesForLevel(student.level) }}
													</td>
													<td>
														{% if student.registrationFee %}
															PAYÉ
														{% else %}
															NON-PAYÉ
														{% endif %}
													</td>
													<td>
														{{ getReason(request.reason) }}
													</td>
													<td>
														{{ request.referenceMobileMoney }}
													</td>
													<td>
														{{ request.doneAt | date('Y-m-d h:m:i') }}
													</td>
													<td>
														{{ request.amount | number_format(null, '.', '.') }}
														Ar
													</td>
													<td>
														<div class="btn-group">
															<button class="btn btn-sm btn-outline-success" title='Valider' data-toggle="modal" data-target="#validation-{{ request.id }}">

																<i class="fas fa-check"></i>
															</button>
															<div class="modal fade" id="validation-{{ request.id }}" tabindex="-1" aria-labelledby="validation-{{ request.id }}Label" aria-hidden="true">

																<div class="modal-dialog">
																	<div class="modal-content">
																		<div class="modal-header">
																			<h5 class="modal-title" id="validation-{{ request.id }}Label">Ètes-vous sur de valider cette paiment ?</h5>
																			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
																				<span aria-hidden="true">&times;</span>
																			</button>
																		</div>

																		<form action="{{ path('app_payment_validate', { id: request.id }) }}" method="POST">
																			<div class="modal-body text-left">

																				<label for="observation">Observation</label>
																				<input type="text" name="observation_{{ request.id }}" class="form-control" id="observation" placeholder="observation ..." value='aucun'>
																			</div>
																			<div class="modal-footer">
																				<button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Fermer</button>
																				<button type="submit" class="btn btn-success">Valider</button>
																			</div>
																		</form>

																	</div>
																</div>
															</div>
															<button class="btn btn-sm btn-outline-danger" title='Annuler'>
																<i class="fas fa-trash"></i>
															</button>
														</td>
													</td>
												</tr>
											</div>
										</tbody>
									</td>
								</tr>
							{% endfor %}
						</tbody>
						<tfoot>
							<tr>
								<th>Photo d'indentité</th>
								<th>Matricule</th>
								<th>Nom complet</th>
								<th>Semestre</th>
								<th>Status écolage</th>
								<th>Status inscription</th>
								<th>Motif</th>
								<th>Référence</th>
								<th>Date de paiment</th>
								<th>Montant</th>
								<th>Actions</th>
							</tr>
						</tfoot>
					</table>
				</div>
			</div>
		</div>
	</div>
</div></div></section></div></div>{{ include('school_manager/layouts/footer.html.twig') }}{% endblock %}